### PR TITLE
snappy support

### PR DESCRIPTION
**Pull request by jmoiron**
Add support for statically compiling the [snappy](http://github.com/google/snappy) compression library and enabling the connector in LevelDB.  This may have some positive impact on the amount of IO used during compaction, at the expense of a little CPU.  Compression is opt-out when we create databases, so there should be no impact in adding this to the main lib.

The Snappy build system is autotools, with an optional CMAKE, but it's simple enough to build.  Most of it is unnecessary for leveldb;  it just needs the stream interface and the basic compression library, so none of the tests get built.  This ends up only being a few files.

The `Makefile` has been altered to have targets `link`, `link_snappy`, and `link_leveldb`, which will create new symlinks for everything, snappy, and leveldb respectively.  The README is updated to reflect this, though the bit about pulling out build options from leveldb wasn't working for me on the current vendored version.

The mainline snappy branch as of this writing has been vendored, https://github.com/google/snappy/commit/7b9532b8781c5beaf99eef8ca7535d969a129d78

Outstanding questions:

- ~does opening a db w/ the snappy compression option enabled when it has been created and written without compression work?~ **yes**, it does;  pages will get compressed upon compaction.  It does _not_ work to have snappy compressed pages in a file and open it with leveldb that does not have snappy support.  LevelDB's compression numbers make their way into the file format, so it's safe to change compression formats on the fly provided you do not drop support for any.
- ~can we get this working in darwin?~ just copying `cgo_snappy_linux.go` and changing the build tag from `//build +linux` to `//build +darwin` worked for me but not for @flapjack103
- does giving snappy a baseline `config.h` with super standard posix stuff change much in terms of perf?
- ~there are [lz4 patches](https://gist.github.com/kevsmith/4217004) out there somewhere;  basho's leveldb fork has it, but it's _significantly_ different;  should we just use that?~ I've ported over the lz4 portions from basho's repo and they were quite small https://github.com/DataDog/leveldb/pull/4/commits/78760f551d64bc8e97d6921debef84333f5ab8a3  the issue is that lz4 will get statically linked here, meaning none of our go libs can use DataDog/golz4 along with it.
- at what point do we stop tuning leveldb and [try rocksdb](http://smalldatum.blogspot.com/2015/04/comparing-leveldb-and-rocksdb-take-2.html) which has a number of clear advantages along the lines that we're now seeing issues (eg write compaction, compaction contention) and more tooling to investigate that behaviour

That last one is an open question.  I intend to get to production using leveldb if possible, but I think leveldb is in use so widely now that it may be good to take a look at what benefits we might get from RocksDB.  Level is no longer under active development whereas Facebook et. al are continuously updating leveldb.

We also might want to rethink our policy on dynamically linking;  it may be less burden in the long run to be able to dynamically link & distribute these libraries using an external build system than it is to make them go-gettable and linked statically.

### CODE REVIEW

**Comment by flapjack103** [comment]
Looks fine to me. I think the more interesting part will be running tests/benchmarks to determine what kind of performance this gives us vs the alternatives you mentioned.

**Comment by jmoiron** [comment]
Does anyone who uses darwin want to give a shot getting this to work in OSX?  @Arkelenia @flapjack103 ?

I'm hesitant to merge now because this _definitely_ does not work.  Snappy is linked into the dir but its headers only get included on linux.  I can break out a laptop I have lying around sometime this evening and try but it might be nice to get this in today if it's a safe change and it makes a good impact.

**Comment by jmoiron** [comment]
Here is some snappy-in-production from earlier today:



2 days are there so the day before can be compared.  The inflection point at 15:30 on day 2 is when the binary was restarted with snappy compression.  It's clear that io utilization started to drop quite a lot, but the trade in user CPU may be too much for this application.

**Comment by jmoiron** [comment]
Production comparison between lz4 and snappy performing under identical loads:



lz4 clearly uses less user CPU and causes less iowait.  The actual IO used is a bit of a complicated story:



It is a slower burn with lz4 (as expected since it produced less iowait) but it ended up being larger.  The two peaks at the end are when these servers were restarted to pick up configuration changes.  As for file sizes, the lz4 leveldb directory for this work period is about 8-10% _smaller_ than the snappy one, 3.4G compared to 3.7G.

**Comment by dd-caleb** [comment]
re rocksdb: https://github.com/DataDog/go-rocksdb

**Comment by jmoiron** [comment]
As to @dd-caleb's comment, that repos is a straight port of levigo to rocksdb, which is ok to get going and a nice starting point for porting extant leveldb apps, but it's missing out on most of the reasons I would want to move my project to LevelDB so I'd probably want to look elsewhere.

I've changed the default compression on this lib to `NoCompression` because anyone using it previously would have not had Snappy available, so the old default of `SnappyCompression` would have basically been `NoCompression` (_even_ if libsnappy was installed on the builders system, the build flags did not include `-DHAVE_SNAPPY`).  This _should_ make this change a noop, aside from making it take slightly longer to build as it now requires building both snappy and LZ4.

I've also added name mangling to the LZ4 lib vendored in this repository so it does not conflict with statically compiled LZ4 in the https://github.com/DataDog/golz4 package (or the original cloudflare fork).

**Pull request merged**
